- name: Import Firewall role
  ansible.builtin.include_role:
    name: common
    tasks_from: firewall

- name: Copying mongodb repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing MongoDB
  ansible.builtin.dnf:
    name: mongodb-org
    state: installed

- name: Updating listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting Mongodb service
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: true

