- name: Installing MySQL
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Starting MySQL service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Changing the default root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

