- name: Import Firewall role
  ansible.builtin.include_role:
    name: common
    tasks_from: firewall

- name: Installing MySQL
  ansible.builtin.dnf:
    name:
      - mysql-server
      - python3-pip
    state: installed

- name: Install PyMySQL via pip
  ansible.builtin.pip:
    name: PyMySQL

- name: Starting MySQL service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Changing the default root password
  community.mysql.mysql_user:
    name: root
    password: RoboShop@1

