- name: Import Firewall role
  ansible.builtin.include_role:
    name: common
    tasks_from: firewall

- name: Importing Golang Role
  ansible.builtin.include_role:
    name: common
    tasks_from: python