- name: Import NodeJS
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name: Copying MongoDB repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing MongoDB
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: Loading Master data
  ansible.builtin.shell: mongosh --host mongodb-dev.pdevops.online </app/db/master-data.js



