- name: Installing GOLANG
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: Import App prerequisites
  ansible.builtin.include_tasks:
    file: app-prereq.yml

- name: Installing GOLANG Dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: Importing Systemd service
  ansible.builtin.include_tasks:
    file: systemd.yml

