- name: Copy application service file
  ansible.builtin.template:
    src: "{{ app_name }}.service"
    dest: /etc/systemd/system/{{ app_name }}.service

- name: Start application service file
  ansible.builtin.systemd_service:
    name: "{{ app_name }}"
    state: restarted
    daemon-reload: true
    enabled: true
